// GENERATED by backend/scripts/build-rail-data.mjs - do not edit by hand (re-run the script).
// Generated 2026-09-19. Sources: LTA MRT Station Exit GeoJSON (data.gov.sg) + OneMap.
// Exit coordinates are { lat, lng } in WGS84; codes/names/order verified against OneMap routes.

export const CCL_STATIONS = [{"code":"CC1","name":"Dhoby Ghaut"},{"code":"CC2","name":"Bras Basah"},{"code":"CC3","name":"Esplanade"},{"code":"CC4","name":"Promenade"},{"code":"CC5","name":"Nicoll Highway"},{"code":"CC6","name":"Stadium"},{"code":"CC7","name":"Mountbatten"},{"code":"CC8","name":"Dakota"},{"code":"CC9","name":"Paya Lebar"},{"code":"CC10","name":"MacPherson"},{"code":"CC11","name":"Tai Seng"},{"code":"CC12","name":"Bartley"},{"code":"CC13","name":"Serangoon"},{"code":"CC14","name":"Lorong Chuan"},{"code":"CC15","name":"Bishan"},{"code":"CC16","name":"Marymount"},{"code":"CC17","name":"Caldecott"},{"code":"CC19","name":"Botanic Gardens"},{"code":"CC20","name":"Farrer Road"},{"code":"CC21","name":"Holland Village"},{"code":"CC22","name":"Buona Vista"},{"code":"CC23","name":"one-north"},{"code":"CC24","name":"Kent Ridge"},{"code":"CC25","name":"Haw Par Villa"},{"code":"CC26","name":"Pasir Panjang"},{"code":"CC27","name":"Labrador Park"},{"code":"CC28","name":"Telok Blangah"},{"code":"CC29","name":"HarbourFront"},{"code":"CC30","name":"Keppel"},{"code":"CC31","name":"Cantonment"},{"code":"CC32","name":"Prince Edward Road"},{"code":"CC33","name":"Marina Bay"},{"code":"CC34","name":"Bayfront"}];

export const SPLRT_STATIONS = [{"code":"SE1","name":"Compassvale"},{"code":"SE2","name":"Rumbia"},{"code":"SE3","name":"Bakau"},{"code":"SE4","name":"Kangkar"},{"code":"SE5","name":"Ranggung"},{"code":"SW1","name":"Cheng Lim"},{"code":"SW2","name":"Farmway"},{"code":"SW3","name":"Kupang"},{"code":"SW4","name":"Thanggam"},{"code":"SW5","name":"Fernvale"},{"code":"SW6","name":"Layar"},{"code":"SW7","name":"Tongkang"},{"code":"SW8","name":"Renjong"},{"code":"PE1","name":"Cove"},{"code":"PE2","name":"Meridian"},{"code":"PE3","name":"Coral Edge"},{"code":"PE4","name":"Riviera"},{"code":"PE5","name":"Kadaloor"},{"code":"PE6","name":"Oasis"},{"code":"PE7","name":"Damai"},{"code":"PW1","name":"Sam Kee"},{"code":"PW2","name":"Teck Lee"},{"code":"PW3","name":"Punggol Point"},{"code":"PW4","name":"Samudera"},{"code":"PW5","name":"Nibong"},{"code":"PW6","name":"Sumang"},{"code":"PW7","name":"Soo Teck"}];

// Exits for stations that are not shared with the North East Line (interchanges reuse NEL exits).
export const EXTRA_STATION_EXITS = {
 "CC2": [
  {
   "exit": "Exit A",
   "lat": 1.296859,
   "lng": 103.851327
  },
  {
   "exit": "Exit B",
   "lat": 1.296046,
   "lng": 103.850474
  },
  {
   "exit": "Exit C",
   "lat": 1.297014,
   "lng": 103.85025
  },
  {
   "exit": "Exit D",
   "lat": 1.297551,
   "lng": 103.850158
  },
  {
   "exit": "Exit E",
   "lat": 1.297535,
   "lng": 103.850423
  }
 ],
 "CC3": [
  {
   "exit": "Exit A",
   "lat": 1.293371,
   "lng": 103.856306
  },
  {
   "exit": "Exit B",
   "lat": 1.292927,
   "lng": 103.856176
  },
  {
   "exit": "Exit C",
   "lat": 1.292904,
   "lng": 103.855855
  },
  {
   "exit": "Exit D",
   "lat": 1.292624,
   "lng": 103.855834
  },
  {
   "exit": "Exit E",
   "lat": 1.293129,
   "lng": 103.855568
  },
  {
   "exit": "Exit F",
   "lat": 1.29382,
   "lng": 103.855105
  },
  {
   "exit": "Exit G",
   "lat": 1.293586,
   "lng": 103.85492
  }
 ],
 "CC4": [
  {
   "exit": "Exit A",
   "lat": 1.291712,
   "lng": 103.860674
  },
  {
   "exit": "Exit B",
   "lat": 1.293862,
   "lng": 103.860137
  },
  {
   "exit": "Exit C",
   "lat": 1.294103,
   "lng": 103.860236
  }
 ],
 "CC5": [
  {
   "exit": "Exit A",
   "lat": 1.30017,
   "lng": 103.863506
  },
  {
   "exit": "Exit B",
   "lat": 1.299661,
   "lng": 103.864152
  }
 ],
 "CC6": [
  {
   "exit": "Exit A",
   "lat": 1.302511,
   "lng": 103.8744
  },
  {
   "exit": "Exit B",
   "lat": 1.30337,
   "lng": 103.876226
  }
 ],
 "CC7": [
  {
   "exit": "Exit A",
   "lat": 1.306753,
   "lng": 103.882598
  },
  {
   "exit": "Exit B",
   "lat": 1.306046,
   "lng": 103.883248
  }
 ],
 "CC8": [
  {
   "exit": "Exit A",
   "lat": 1.308814,
   "lng": 103.889307
  },
  {
   "exit": "Exit B",
   "lat": 1.308097,
   "lng": 103.887979
  }
 ],
 "CC9": [
  {
   "exit": "Exit A",
   "lat": 1.318216,
   "lng": 103.892788
  },
  {
   "exit": "Exit B",
   "lat": 1.318347,
   "lng": 103.892217
  },
  {
   "exit": "Exit C",
   "lat": 1.318149,
   "lng": 103.891721
  },
  {
   "exit": "Exit D",
   "lat": 1.316588,
   "lng": 103.892078
  }
 ],
 "CC10": [
  {
   "exit": "Exit A",
   "lat": 1.326679,
   "lng": 103.889793
  },
  {
   "exit": "Exit B",
   "lat": 1.325855,
   "lng": 103.890666
  },
  {
   "exit": "Exit C",
   "lat": 1.325482,
   "lng": 103.890263
  },
  {
   "exit": "Exit D",
   "lat": 1.325145,
   "lng": 103.888455
  },
  {
   "exit": "Exit E",
   "lat": 1.326193,
   "lng": 103.888615
  }
 ],
 "CC11": [
  {
   "exit": "C",
   "lat": 1.335772,
   "lng": 103.888261
  },
  {
   "exit": "Exit A",
   "lat": 1.335914,
   "lng": 103.887627
  },
  {
   "exit": "Exit B",
   "lat": 1.334621,
   "lng": 103.888214
  }
 ],
 "CC12": [
  {
   "exit": "Exit A",
   "lat": 1.342249,
   "lng": 103.880256
  },
  {
   "exit": "Exit B",
   "lat": 1.343501,
   "lng": 103.878909
  }
 ],
 "CC14": [
  {
   "exit": "Exit A",
   "lat": 1.351439,
   "lng": 103.864934
  },
  {
   "exit": "Exit B",
   "lat": 1.351739,
   "lng": 103.862918
  }
 ],
 "CC15": [
  {
   "exit": "Exit A",
   "lat": 1.35058,
   "lng": 103.848305
  },
  {
   "exit": "Exit B",
   "lat": 1.351064,
   "lng": 103.848312
  },
  {
   "exit": "Exit C",
   "lat": 1.350585,
   "lng": 103.848209
  },
  {
   "exit": "Exit D",
   "lat": 1.351053,
   "lng": 103.850201
  },
  {
   "exit": "Exit E",
   "lat": 1.351035,
   "lng": 103.848433
  }
 ],
 "CC16": [
  {
   "exit": "Exit A",
   "lat": 1.34898,
   "lng": 103.839088
  },
  {
   "exit": "Exit B",
   "lat": 1.347866,
   "lng": 103.840059
  }
 ],
 "CC17": [
  {
   "exit": "Exit 1",
   "lat": 1.337105,
   "lng": 103.839407
  },
  {
   "exit": "Exit 2",
   "lat": 1.33826,
   "lng": 103.840387
  },
  {
   "exit": "Exit 3",
   "lat": 1.337832,
   "lng": 103.840465
  },
  {
   "exit": "Exit 4",
   "lat": 1.336751,
   "lng": 103.839882
  }
 ],
 "CC19": [
  {
   "exit": "Exit A",
   "lat": 1.322535,
   "lng": 103.814977
  },
  {
   "exit": "Exit B",
   "lat": 1.322685,
   "lng": 103.815914
  }
 ],
 "CC20": [
  {
   "exit": "Exit A",
   "lat": 1.317494,
   "lng": 103.807965
  },
  {
   "exit": "Exit B",
   "lat": 1.317552,
   "lng": 103.807389
  }
 ],
 "CC21": [
  {
   "exit": "Exit A",
   "lat": 1.31122,
   "lng": 103.796139
  },
  {
   "exit": "Exit B",
   "lat": 1.311069,
   "lng": 103.795769
  },
  {
   "exit": "Exit C",
   "lat": 1.310711,
   "lng": 103.795754
  }
 ],
 "CC22": [
  {
   "exit": "Exit A",
   "lat": 1.307309,
   "lng": 103.790449
  },
  {
   "exit": "Exit B",
   "lat": 1.307197,
   "lng": 103.790657
  },
  {
   "exit": "Exit C",
   "lat": 1.306913,
   "lng": 103.790599
  },
  {
   "exit": "Exit D",
   "lat": 1.306298,
   "lng": 103.79093
  }
 ],
 "CC23": [
  {
   "exit": "Exit A",
   "lat": 1.299027,
   "lng": 103.786907
  },
  {
   "exit": "Exit B",
   "lat": 1.300359,
   "lng": 103.787928
  },
  {
   "exit": "Exit C",
   "lat": 1.299715,
   "lng": 103.787565
  },
  {
   "exit": "Exit D",
   "lat": 1.300075,
   "lng": 103.787785
  }
 ],
 "CC24": [
  {
   "exit": "Exit A",
   "lat": 1.294316,
   "lng": 103.784466
  },
  {
   "exit": "Exit B",
   "lat": 1.292428,
   "lng": 103.78481
  },
  {
   "exit": "Exit C",
   "lat": 1.293985,
   "lng": 103.78449
  },
  {
   "exit": "Exit D",
   "lat": 1.293219,
   "lng": 103.784535
  }
 ],
 "CC25": [
  {
   "exit": "Exit A",
   "lat": 1.283055,
   "lng": 103.782006
  }
 ],
 "CC26": [
  {
   "exit": "Exit A",
   "lat": 1.276003,
   "lng": 103.79203
  }
 ],
 "CC27": [
  {
   "exit": "Exit A",
   "lat": 1.272107,
   "lng": 103.802356
  }
 ],
 "CC28": [
  {
   "exit": "Exit A",
   "lat": 1.270721,
   "lng": 103.809884
  }
 ],
 "CC30": [
  {
   "exit": "Exit 1",
   "lat": 1.269559,
   "lng": 103.82963
  },
  {
   "exit": "Exit 2",
   "lat": 1.270604,
   "lng": 103.830801
  },
  {
   "exit": "Exit 3",
   "lat": 1.270532,
   "lng": 103.829683
  }
 ],
 "CC31": [
  {
   "exit": "Exit 1",
   "lat": 1.272084,
   "lng": 103.835651
  },
  {
   "exit": "Exit 2",
   "lat": 1.27389,
   "lng": 103.835986
  },
  {
   "exit": "Exit 3",
   "lat": 1.27358,
   "lng": 103.838087
  }
 ],
 "CC32": [
  {
   "exit": "Exit 1",
   "lat": 1.273018,
   "lng": 103.845592
  },
  {
   "exit": "Exit 2",
   "lat": 1.273438,
   "lng": 103.846889
  }
 ],
 "CC33": [
  {
   "exit": "Exit 1",
   "lat": 1.277353,
   "lng": 103.85447
  },
  {
   "exit": "Exit 2",
   "lat": 1.276159,
   "lng": 103.855003
  },
  {
   "exit": "Exit 3",
   "lat": 1.275416,
   "lng": 103.855372
  },
  {
   "exit": "Exit 4",
   "lat": 1.273634,
   "lng": 103.856489
  },
  {
   "exit": "Exit 5",
   "lat": 1.274693,
   "lng": 103.85432
  }
 ],
 "CC34": [
  {
   "exit": "Exit A",
   "lat": 1.280967,
   "lng": 103.858732
  },
  {
   "exit": "Exit B",
   "lat": 1.282705,
   "lng": 103.859759
  },
  {
   "exit": "Exit C",
   "lat": 1.282835,
   "lng": 103.859597
  },
  {
   "exit": "Exit D",
   "lat": 1.282834,
   "lng": 103.859494
  },
  {
   "exit": "Exit E",
   "lat": 1.281105,
   "lng": 103.858441
  }
 ],
 "SE1": [
  {
   "exit": "Exit A",
   "lat": 1.394328,
   "lng": 103.900616
  },
  {
   "exit": "Exit B",
   "lat": 1.394534,
   "lng": 103.900707
  }
 ],
 "SE2": [
  {
   "exit": "Exit A",
   "lat": 1.39134,
   "lng": 103.906019
  },
  {
   "exit": "Exit B",
   "lat": 1.391414,
   "lng": 103.906106
  }
 ],
 "SE3": [
  {
   "exit": "Exit A",
   "lat": 1.388185,
   "lng": 103.905446
  },
  {
   "exit": "Exit B",
   "lat": 1.387841,
   "lng": 103.905482
  }
 ],
 "SE4": [
  {
   "exit": "Exit A",
   "lat": 1.384075,
   "lng": 103.902148
  },
  {
   "exit": "Exit B",
   "lat": 1.383765,
   "lng": 103.902276
  }
 ],
 "SE5": [
  {
   "exit": "Exit A",
   "lat": 1.384176,
   "lng": 103.897322
  },
  {
   "exit": "Exit B",
   "lat": 1.384105,
   "lng": 103.897224
  }
 ],
 "SW1": [
  {
   "exit": "Exit A",
   "lat": 1.396373,
   "lng": 103.893685
  },
  {
   "exit": "Exit B",
   "lat": 1.396187,
   "lng": 103.89392
  }
 ],
 "SW2": [
  {
   "exit": "Exit A",
   "lat": 1.3972,
   "lng": 103.889407
  },
  {
   "exit": "Exit B",
   "lat": 1.397133,
   "lng": 103.889115
  }
 ],
 "SW3": [
  {
   "exit": "Exit A",
   "lat": 1.398284,
   "lng": 103.881139
  },
  {
   "exit": "Exit B",
   "lat": 1.398159,
   "lng": 103.881138
  }
 ],
 "SW4": [
  {
   "exit": "Exit A",
   "lat": 1.397198,
   "lng": 103.875566
  },
  {
   "exit": "Exit B",
   "lat": 1.397192,
   "lng": 103.875687
  }
 ],
 "SW5": [
  {
   "exit": "Exit A",
   "lat": 1.392158,
   "lng": 103.876262
  }
 ],
 "SW6": [
  {
   "exit": "Exit A",
   "lat": 1.392026,
   "lng": 103.88016
  },
  {
   "exit": "Exit B",
   "lat": 1.392145,
   "lng": 103.880143
  }
 ],
 "SW7": [
  {
   "exit": "Exit A",
   "lat": 1.38918,
   "lng": 103.885962
  },
  {
   "exit": "Exit B",
   "lat": 1.389379,
   "lng": 103.886084
  }
 ],
 "SW8": [
  {
   "exit": "Exit A",
   "lat": 1.386698,
   "lng": 103.890409
  },
  {
   "exit": "Exit B",
   "lat": 1.386814,
   "lng": 103.890438
  }
 ],
 "PE1": [
  {
   "exit": "Exit A",
   "lat": 1.399124,
   "lng": 103.905929
  },
  {
   "exit": "Exit B",
   "lat": 1.399303,
   "lng": 103.906176
  }
 ],
 "PE2": [
  {
   "exit": "Exit A",
   "lat": 1.396681,
   "lng": 103.908966
  },
  {
   "exit": "Exit B",
   "lat": 1.397122,
   "lng": 103.908869
  }
 ],
 "PE3": [
  {
   "exit": "Exit A",
   "lat": 1.393685,
   "lng": 103.912652
  },
  {
   "exit": "Exit B",
   "lat": 1.393971,
   "lng": 103.912709
  }
 ],
 "PE4": [
  {
   "exit": "Exit A",
   "lat": 1.394326,
   "lng": 103.916263
  },
  {
   "exit": "Exit B",
   "lat": 1.394559,
   "lng": 103.915935
  }
 ],
 "PE5": [
  {
   "exit": "Exit A",
   "lat": 1.399809,
   "lng": 103.916387
  },
  {
   "exit": "Exit B",
   "lat": 1.399411,
   "lng": 103.916517
  }
 ],
 "PE6": [
  {
   "exit": "Exit A",
   "lat": 1.402507,
   "lng": 103.912646
  },
  {
   "exit": "Exit B",
   "lat": 1.402104,
   "lng": 103.912755
  }
 ],
 "PE7": [
  {
   "exit": "Exit A",
   "lat": 1.405285,
   "lng": 103.908792
  },
  {
   "exit": "Exit B",
   "lat": 1.405046,
   "lng": 103.908614
  }
 ],
 "PW1": [
  {
   "exit": "Exit A",
   "lat": 1.409703,
   "lng": 103.905039
  },
  {
   "exit": "Exit B",
   "lat": 1.409828,
   "lng": 103.904792
  }
 ],
 "PW2": [
  {
   "exit": "Exit A",
   "lat": 1.412876,
   "lng": 103.906782
  },
  {
   "exit": "Exit B",
   "lat": 1.412929,
   "lng": 103.906511
  }
 ],
 "PW3": [
  {
   "exit": "Exit A",
   "lat": 1.416915,
   "lng": 103.906818
  },
  {
   "exit": "Exit B",
   "lat": 1.416664,
   "lng": 103.906693
  }
 ],
 "PW4": [
  {
   "exit": "Exit A",
   "lat": 1.415865,
   "lng": 103.901912
  },
  {
   "exit": "Exit B",
   "lat": 1.415906,
   "lng": 103.902362
  }
 ],
 "PW5": [
  {
   "exit": "Exit A",
   "lat": 1.411773,
   "lng": 103.900074
  },
  {
   "exit": "Exit B",
   "lat": 1.41191,
   "lng": 103.900532
  }
 ],
 "PW6": [
  {
   "exit": "Exit A",
   "lat": 1.408368,
   "lng": 103.898336
  },
  {
   "exit": "Exit B",
   "lat": 1.408488,
   "lng": 103.898757
  }
 ],
 "PW7": [
  {
   "exit": "Exit A",
   "lat": 1.405015,
   "lng": 103.89703
  },
  {
   "exit": "Exit B",
   "lat": 1.405245,
   "lng": 103.897409
  }
 ]
};
