export const NEL_STATIONS = [
  { code: "NE1", name: "HarbourFront", mapX: 47.5, mapY: 67.5, interchange: true },
  { code: "NE3", name: "Outram Park", mapX: 43.8, mapY: 61.8, interchange: true },
  { code: "NE4", name: "Chinatown", mapX: 45.8, mapY: 58.8, interchange: true },
  { code: "NE5", name: "Clarke Quay", mapX: 47.9, mapY: 55.9 },
  { code: "NE6", name: "Dhoby Ghaut", mapX: 49.6, mapY: 52.2, interchange: true },
  { code: "NE7", name: "Little India", mapX: 52.0, mapY: 48.8, interchange: true },
  { code: "NE8", name: "Farrer Park", mapX: 53.8, mapY: 46.3 },
  { code: "NE9", name: "Boon Keng", mapX: 56.0, mapY: 43.8 },
  { code: "NE10", name: "Potong Pasir", mapX: 59.0, mapY: 40.8 },
  { code: "NE11", name: "Woodleigh", mapX: 62.0, mapY: 37.9 },
  { code: "NE12", name: "Serangoon", mapX: 65.2, mapY: 35.1, interchange: true },
  { code: "NE13", name: "Kovan", mapX: 69.1, mapY: 31.9 },
  { code: "NE14", name: "Hougang", mapX: 72.1, mapY: 29.1 },
  { code: "NE15", name: "Buangkok", mapX: 76.0, mapY: 26.4 },
  { code: "NE16", name: "Sengkang", mapX: 79.4, mapY: 23.3, interchange: true },
  { code: "NE17", name: "Punggol", mapX: 82.2, mapY: 20.0, interchange: true },
  { code: "NE18", name: "Punggol Coast", mapX: 84.2, mapY: 16.8 },
];

export const FAVORITE_STATION_CODES = ["NE6", "NE7", "NE12"];

// ---------------------------------------------------------------------------
// Network model: the North East Line (curated above) plus the Circle Line and the Sengkang-Punggol LRT
// (generated by backend/scripts/build-rail-data.mjs into railData.js). Codes, names and ring/arm structure
// were verified against real OneMap routes: Circle Line Stage 6 is open, so it is a full ring
// (CC4 ... CC29 -> CC30 ... CC34 -> back to CC4) with a short arm CC1-CC2-CC3 into Promenade, and each LRT
// branch is a ring that starts and ends at its hub (OneMap calls the hubs STC and PTC).
// ---------------------------------------------------------------------------
import { CCL_STATIONS, SPLRT_STATIONS } from "./railData.js";

// A station shared between lines has one physical record; the code used on the OTHER line points at it.
export const CODE_ALIASES = { CC1: "NE6", CC13: "NE12", CC29: "NE1", STC: "NE16", PTC: "NE17" };

const ring = (prefix, n, hub) => ({ codes: [hub, ...Array.from({ length: n }, (_, i) => `${prefix}${i + 1}`)], ring: true });
const CCL_LOOP_CODES = CCL_STATIONS.map((s) => s.code).filter((c) => Number(c.slice(2)) >= 4);

export const LINES = {
  NEL: {
    id: "NEL",
    name: "North East Line",
    short: "NEL",
    routeIds: ["NE"],
    mode: "SUBWAY",
    color: "#8055bb",
    branches: [{ name: "North East Line", codes: NEL_STATIONS.map((s) => s.code), ring: false }],
  },
  CCL: {
    id: "CCL",
    name: "Circle Line",
    short: "CCL",
    routeIds: ["CC"],
    mode: "SUBWAY",
    color: "#fa9e0d",
    branches: [
      { name: "Dhoby Ghaut arm", codes: ["CC1", "CC2", "CC3", "CC4"], ring: false },
      { name: "Circle Line loop", codes: CCL_LOOP_CODES, ring: true },
    ],
  },
  SPLRT: {
    id: "SPLRT",
    name: "Sengkang-Punggol LRT",
    short: "LRT",
    routeIds: ["SE", "SW", "PE", "PW"],
    mode: "TRAM",
    color: "#748477",
    branches: [
      { name: "Sengkang East Loop", ...ring("SE", 5, "STC") },
      { name: "Sengkang West Loop", ...ring("SW", 8, "STC") },
      { name: "Punggol East Loop", ...ring("PE", 7, "PTC") },
      { name: "Punggol West Loop", ...ring("PW", 7, "PTC") },
    ],
  },
};
export const LINE_IDS = Object.keys(LINES);

export function canonicalCode(code) {
  return CODE_ALIASES[code] || code;
}

// Physical stations, keyed by canonical code. NEL records keep their curated fields (mapX/mapY, ...).
const PHYSICAL = new Map();
for (const s of NEL_STATIONS) PHYSICAL.set(s.code, { ...s, codes: [s.code], lines: ["NEL"] });
function addStation(lineId, { code, name }) {
  const canon = canonicalCode(code);
  const existing = PHYSICAL.get(canon);
  if (existing) {
    if (!existing.codes.includes(code)) existing.codes.push(code);
    if (!existing.lines.includes(lineId)) existing.lines.push(lineId);
  } else {
    PHYSICAL.set(canon, { code: canon, name, codes: [code], lines: [lineId] });
  }
}
CCL_STATIONS.forEach((s) => addStation("CCL", s));
SPLRT_STATIONS.forEach((s) => addStation("SPLRT", s));

export const ALL_STATIONS = [...PHYSICAL.values()];

export function stationByCode(code) {
  return PHYSICAL.get(canonicalCode(code));
}

export function stationIndex(code) {
  return NEL_STATIONS.findIndex((s) => s.code === code);
}

export function lineIdForCode(code) {
  if (/^NE\d/.test(code)) return "NEL";
  if (/^CC\d/.test(code)) return "CCL";
  if (/^(SE|SW|PE|PW)\d/.test(code) || code === "STC" || code === "PTC") return "SPLRT";
  return null;
}

// Ordered station groups for a line, e.g. one group for the NEL, four loops for the LRT.
// Each station also carries `lineCode`: the code it has ON THIS LINE (Dhoby Ghaut is NE6 but CC1 on the Circle Line).
export function lineGroups(lineId) {
  const line = LINES[lineId];
  const seen = new Set();
  return line.branches
    .map((b) => ({
      name: b.name,
      stations: b.codes
        .filter((c) => lineId === "SPLRT" || !seen.has(c) ? (seen.add(c), true) : false)
        .map((c) => ({ ...stationByCode(c), lineCode: c }))
        .filter((s) => s.name),
    }))
    .filter((g) => g.stations.length > 0);
}

// Physical stations of a line with a single flat, de-duplicated order (for search and counts).
export function lineStations(lineId) {
  const out = [];
  const seen = new Set();
  for (const g of lineGroups(lineId)) for (const s of g.stations) if (!seen.has(s.code)) (seen.add(s.code), out.push(s));
  return out;
}

// Adjacency per line, built from the branches (rings add a last->first edge).
const GRAPHS = Object.fromEntries(
  LINE_IDS.map((id) => {
    const adj = new Map();
    const link = (a, b) => {
      if (!adj.has(a)) adj.set(a, new Set());
      if (!adj.has(b)) adj.set(b, new Set());
      adj.get(a).add(b);
      adj.get(b).add(a);
    };
    for (const b of LINES[id].branches) {
      b.codes.forEach((c, i) => i > 0 && link(b.codes[i - 1], c));
      if (b.ring && b.codes.length > 2) link(b.codes[b.codes.length - 1], b.codes[0]);
    }
    return [id, adj];
  })
);

/**
 * Ordered [{ code, name }] of the stations between two codes of the SAME line (inclusive), by shortest path
 * along the line's own topology - rings and the Circle Line arm included. [] if they aren't on one line.
 */
export function pathBetween(fromCode, toCode) {
  const lineId = lineIdForCode(fromCode);
  if (!lineId || lineId !== lineIdForCode(toCode)) return [];
  const adj = GRAPHS[lineId];
  if (!adj.has(fromCode) || !adj.has(toCode)) return [];
  const prev = new Map([[fromCode, null]]);
  const queue = [fromCode];
  while (queue.length && !prev.has(toCode)) {
    const cur = queue.shift();
    for (const n of adj.get(cur)) if (!prev.has(n)) (prev.set(n, cur), queue.push(n));
  }
  if (!prev.has(toCode)) return [];
  const path = [];
  for (let c = toCode; c !== null; c = prev.get(c)) path.push(c);
  return path.reverse().map((c) => ({ code: c, name: stationByCode(c)?.name || c }));
}

// MRT (not LRT) station codes: what a cyclist can sensibly ride to.
export const MRT_STATION_CODES = ALL_STATIONS.filter((s) => s.lines.some((l) => l !== "SPLRT")).map((s) => s.code);
